[tool.poetry]
name = "trf"
version = "0.1.0"
description = ""
authors = ["Gregorio Honorato <greghono@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mechanize = "^0.4.8"
bs4 = "^0.0.1"
pillow = "^10.0.0"
pytesseract = "^0.3.10"
opencv-python = "^4.8.0.76"
selenium = "^4.11.2"
h5py = "^3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
